workspace = { members = ["sse-device-client", "sse-device-server", "svckit"] }
[package]
name = "sse-device-upgrade-svc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
